### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#124]
What about CSRF protection for HTTP request methods?

**Comment by letr0n** [comment]
Hi

You can use the ```$session->generateToken()``` and ```$session->validateToken()``` methods.

They will generate and validate a single use token that can be used to secure forms. 

You can also use the ```token```validation rule to validate it (http://makoframework.com/docs/4.3/learn-more:validation#validation_rules)

**Comment by ConsoleTVs** [comment]
Alright let me try to use it, and see how it goes, thanks for the info!

**Comment by ConsoleTVs** [comment]
@letr0n Worked fine!
