### ISSUE TITLE
Add getter/setter for Formatter::$hasAnsiSupport

### ISSUE THREAD

**Issue by telephone** [mako-framework/framework#129]
__Version 4.4__

I'd like to have `--ansi` and `--no-ansi` as global options within Reactor. The only limitation is ANSI support can only be triggered via the `Formatter::__construct()`.

^ I'm triggering my own instance of `cli\Application`... In saying that though, I think these should be included as global options of the CLI.

---

A few options to consider:

1. Getter/Setter for `Formatter::$hasAnsiSupport`.
2. Change visibility of `Formatter::$hasAnsiSupport` to public, so it can be set via `$output->getFormatter()->hasAnsiSupport`.
3. Add `Output::setFormatter()`.

**Comment by letr0n** [comment]
I think version 3 would be the best way to change this as it requires the least amount of changes to the core.

**Comment by freost** [comment]
I have added a ```Output::setFormatter()``` method. 

I'll release 4.4.1 in a few days ... just waiting to see if there are other fixes/tweaks that are needed :)
