### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by telephone** [mako-framework/framework#130]
This ones more of a pet peeve, but I've noticed across all the projects (framework, app, and toolbar) there's a lot of trailing whitespace leftover from the IDE/editor.

In `mako-framework/framework` alone, there's 248 PHP files with trailing whitespace.

__Example:__

![mako-whitespace2](https://cloud.githubusercontent.com/assets/1809542/5949305/28b3fcec-a7b1-11e4-999c-ebedb27a739b.png)

__Temporary Solution:__

Use [PHP-CS-FIXER](http://cs.sensiolabs.org) to remove trailing whitespace:

```
1) curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar
2) php php-cs-fixer.phar fix src/mako --fixers=trailing_spaces,whitespacy_lines

Optional:
- Add --dry-run to #2 to view filenames that need fixing
- Add --dry-run --diff to #2 to output a diff of the changes (best to output to file)
```

__Permanent Solutions:__

1) Include an [.editorconfig](http://editorconfig.org) file in the repo's root to ensure coding standards are in-sync. (Note: You'll still have to apply the temporary solution)

Here's an example that would work for mako:
```
# top-most EditorConfig file
root = true

# Only apply to PHP files:
# UTF-8, Unix line endings, Tab indention (1 tab = 4 spaces), Trim trailing whitespace on save
[*.php]
charset = utf-8
end_of_line = lf
indent_style = tab
tab_width = 4
trim_trailing_whitespace = true
```
2) Run [PHP-CS-FIXER](http://cs.sensiolabs.org) before each release. While this option doesn't stay on-top of the issue, it at least allows each release to have a clean slate.

3) Write a pre-commit hook for git that will run [PHP-CS-FIXER](http://cs.sensiolabs.org) with the designated coding standards. I can easily code one up if needed...

4) Enable `Strip trailing spaces on Save` for your given editor. (Note: You'll still have to apply the temporary solution).

---

At the end of the day, it comes down to the developers preferences... And I'm a bit of a whitespace-natzi when it comes to PHP :neckbeard:.  
Personally I've used all the options above for different projects, but [.editorconfig](http://editorconfig.org) is usually the easiest as it's available as a plugin for almost every IDE/editor.

**Comment by freost** [comment]
I have no problems with getting rid of all trailing whitespace :stuck_out_tongue: 

I made a couple of commits where I removed all of it using the php-cs-fixer and I have also added a .editconfig file. (I'll do the same of the the skeleton app and the toolbar).

I'll look into adding pre-commit hook. Wouldn't it require people to have php-cs-fixer installer?

**Comment by telephone** [comment]
> I'll look into adding pre-commit hook. Wouldn't it require people to have php-cs-fixer installer?

Pre-commits are local only (not supported by Github), and have to be manually setup. These hooks are normally done within teams so standards, tests, etc are checked before commit/code review.

Since pre-commits can use any language, the pre-commit can use PHP. From there you can check for  `php-cs-fixer.phar`, if not available then download (or if older than X days update).

As I mentioned above, I can code one tomorrow if you'd like?

---

The other option I can think of would be to tie [Scrutinizer](https://scrutinizer-ci.com) into Travis CI. Scrutinizer is free for open-source projects :smile:.

You can heavily customize the allowed coding standards, and add whitespace checks among many others. [Mockery](https://github.com/padraic/mockery) is an example as they've tied their Scrutinizer checks into Travis CI.

Scrutinizer also gives you the option of "[Automated Fix](https://scrutinizer-ci.com/docs/tools/automated-fixes/)" which can send a patch, or a pull request with the given changes. The automated fixes can also apply to [pull requests](https://scrutinizer-ci.com/blog/pull-request-support-for-patches).

List of automated fixes:

![scrutinizer](https://cloud.githubusercontent.com/assets/1809542/5959104/3c0dd8ba-a830-11e4-979c-68fd6a5ae174.png)

**Comment by letr0n** [comment]
Awesome to get rid of the white space :+1: I had a go at creating a pre-commit hook It's pretty basic but it should work. Not sure where it would be best to place it though.

	#!/usr/bin/php
	<?php

	function php_cs_fixer()
	{
		static $fixer;

		if($fixer === null)
		{
			$fixer = shell_exec('which php-cs-fixer');

			if(empty($fixer))
			{
				exit(1);
			}
		}

		return $fixer;
	}

	exec('git diff --name-only', $output);

	foreach($output as $file)
	{
		exec(php_cs_fixer() . ' fix ' . $file . ' --fixers=trailing_spaces,whitespacy_lines');
	}

**Comment by telephone** [comment]
@letr0n I'd say either in a folder `git_tools/hooks` or in a separate repo depending how much logic is used.

Some things I'd prefer to have:
- Only fix the staged lines (you can stage 1 line from a 1000 line file)
- Only fix added files (exclude deleted files)

In saying that, I went back through some old projects and found this pre-commit script that I edited for PHP files:

```bash
#!/bin/bash
####
# A git hook script to find and fix trailing whitespace in your commits. Bypass
# it with the --no-verify option to git-commit.
#
# Usage:
#   1) Ensure file is executable:
#        chmod +x pre-commit.git.sh
#   2) Make a soft link to this file:
#        ln -s ~/config/pre-commit.git.sh ~/some_project/.git/hooks/pre-commit
####

# credits:
# http://makandracards.com/makandra/11541-how-to-not-leave-trailing-whitespace-using-your-editor-or-git
# https://github.com/philz/snippets/blob/master/pre-commit-remove-trailing-whitespace.sh
# https://github.com/imoldman/config/blob/master/pre-commit.git.sh

# file-extension filter (regex)
file_ext="\.php$"

# detect platform
platform="win"
uname_result=`uname`
if [[ "$uname_result" == "Linux" ]]; then
  platform="linux"
elif [[ "$uname_result" == "Darwin" ]]; then
  platform="mac"
fi

# change IFS to ignore filename's space in |for|
IFS="
"

# remove trailing whitespace in modified lines
for line in `git diff --check --cached | sed '/^[+-]/d'`; do
  # get file name
  if [[ "$platform" == "mac" ]]; then
    file="`echo $line | sed -E 's/:[0-9]+: .*//'`"
    line_number="`echo $line | sed -E 's/.*:([0-9]+).*/\1/'`"
  else
    file="`echo $line | sed -r 's/:[0-9]+: .*//'`"
    line_number="`echo $line | sed -r 's/.*:([0-9]+).*/\1/'`"
  fi

  # only process {file-extension filter} files (unsure if cross-OS compatible)
  if [[ ! $file =~ $file_ext ]]; then
    continue
  fi

  # since $file in working directory isn't always equal to $file in index,
  # we backup it; thereby we can add our whitespace fixes without accidently
  # adding unstaged changes
  backup_file="${file}.working_directory_backup"
  cat "$file" > "$backup_file"
  git checkout -- "$file" # discard unstaged changes in working directory

  # remove trailing whitespace in $file (modified lines only)
  if [[ "$platform" == "win" ]]; then
    # in windows, `sed -i` adds ready-only attribute to $file (I don't kown why), so we use temp file instead
    sed "${line_number}s/[[:space:]]*$//" "$file" > "${file}.bak"
    mv -f "${file}.bak" "$file"
  elif [[ "$platform" == "mac" ]]; then
    sed -i "" "${line_number}s/[[:space:]]*$//" "$file"
  else
    sed -i "${line_number}s/[[:space:]]*$//" "$file"
  fi
  git add "$file" # to index, so our whitespace changes will be committed

  # restore unstaged changes in $file from its working directory backup, fixing
  # whitespace that we fixed above
  sed "${line_number}s/[[:space:]]*$//" "$backup_file" > "$file"
  rm "$backup_file"

  [[ "$platform" == "mac" ]] || e_option="-e" # mac does not understand -e
  echo $e_option "Removed trailing whitespace in \"$file\"; Line $line_number"
done

echo

# from template file
if git rev-parse --verify HEAD; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If there still are whitespace errors, print the offending file names and fail.
for line in `git diff-index --check --cached ${against} -- | sed '/^[+-]/d'`; do
  if [[ "$platform" == "mac" ]]; then
    file="`echo $line | sed -E 's/:[0-9]+: .*//'`"
    line_number="`echo $line | sed -E 's/.*:([0-9]+).*/\1/'`"
  else
    file="`echo $line | sed -r 's/:[0-9]+: .*//'`"
    line_number="`echo $line | sed -r 's/.*:([0-9]+).*/\1/'`"
  fi

  if [[ ! $file =~ $file_ext ]]; then
    continue
  fi

  [[ "$platform" == "mac" ]] || e_option="-e"
  echo $e_option "Failed to remove trailing whitespace in \"$file\"; Line $line_number"
done

# Now we can commit
exit
```

The output is the following:

```
Removed trailing whitespace in "Folder/TestFile.php"; Line 3
Removed trailing whitespace in "Folder/TestFile.php"; Line 9
Removed trailing whitespace in "Folder/TestFile.php"; Line 13
```

---

Note: I've only used this in a Linux environment so unsure if it's truly cross-OS compatible.

**Comment by letr0n** [comment]
Made a better version (and even tested it this time :stuck_out_tongue: 

	#!/usr/bin/php
	<?php

	// Check if we have php-cs-fixer in the path and exit if we don't

	$fixer = trim(shell_exec('which php-cs-fixer'));

	if(empty($fixer))
	{
		exit(1);
	}

	// Get the list of modified files and run PHP files through the php-cs-fixer

	exec('git diff --cached --name-status', $output);

	foreach($output as $file)
	{
		if(substr($file, 0, 1) !== 'M')
		{
			continute; // File isn't modified so we'll just skip it
		}

		$file = trim(substr($file, 1));

		if(file_exists($file) && pathinfo($file, PATHINFO_EXTENSION) === 'php')
		{
			exec(PHP_BINARY . ' ' . $fixer . ' fix ' . $file . ' --fixers=trailing_spaces,whitespacy_lines');

			exec('git add ' . $file);
		}
	}

**Comment by freost** [comment]
Sure I can set up a repo for git hooks :+1:

**Comment by freost** [comment]
Repo is up.
