### ISSUE TITLE
CLI: Alphabetical sort for global options

### ISSUE THREAD

**Issue by telephone** [mako-framework/framework#132]
__Version 4.4__

I noticed you implemented a `ksort()` for commands in 4.4 :thumbsup:, but I'd also like to request `sort()` for the global options (in `Reactor::getOptions`).

^ Again, using my own `cli\Application` instance, and I'd prefer to have the global options alphabetical, rather than `--mute` being on-top.

**Comment by freost** [comment]
Good idea. I'll implement that right away.
