### ISSUE TITLE
Named routes

### ISSUE THREAD

**Issue by telephone** [mako-framework/framework#133]
I'd like to request a way to return the current route name (if using named routes).

I looked through the code but couldn't find this, so please correct me if I'm wrong, but it appears there's no method to retrieve the current route name.

E.g. Via Laravel you can use `Route::currentRouteName();`.

Unsure where the most suitable place for it would be, but `Routes::currentNamedRoute()` would be good. That way it's accessible via container.
I'd say only returning the name itself is sufficient, as if the user wants more information they can plug the name into `Routes::getNamedRoute()`.

**Comment by freost** [comment]
I'll try to find the best way to implement this and include it in the next version.

**Comment by freost** [comment]
Fixed by d73469447995fcf1101c5a93f20f8a195e4935e9. You'll be able to get the route using ```$request->getRoute()```.
