### ISSUE TITLE
Check Auth in route

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#134]
Hello there must be a way to check if the user is logged in in the route instead of using the same code 192'31239 times in each protected function, is there a way to do it with ->before or ->when? thanks!

**Comment by freost** [comment]
Hi,

You can create a [route filter](http://makoframework.com/docs/4.4/routing-and-controllers:routing#route_filters) and apply it to a route group.

```php
$routes->group(['before' => 'auth.check_login'], function($routes)
{
   // put all your protected routes in here
});
```

**Comment by ConsoleTVs** [comment]
Where are things like: auth.check_login documented? Thanks a lot!

**Comment by ConsoleTVs** [comment]
Nvm i had to define the route;

But still got questions!

(this is my first frameworks so don't git me pls :D )

http://puu.sh/fhCl9/1ee2d55d81.png

If you look at this I get an error saing: 

Undefined property: mako\application\Web::$gatekeeper

**Comment by letr0n** [comment]
You have to inject gatekeeper (requires Mako 4.3+) :)

```php
<?php

use mako\auth\Gatekeeper;

$filters->register('auth.check_login', function(Gatekeeper $gatekeeper))
{
	// Your code here	
});
```

**Comment by ConsoleTVs** [comment]
Yeah i was doing that, I evaded that error, but the cool thing is that it always returns i am not logged in, I am trying to fix that

Hold on

**Comment by ConsoleTVs** [comment]
You forgot to remove the last ) in the $filters line :3

**Comment by ConsoleTVs** [comment]
Alright, I got this code:

use mako\auth\gatekeeper;


$filters->register('auth.check_login', function(gatekeeper $gatekeeper)
{
	$isLoggedIn = $this->gatekeeper->isLoggedIn();
	var_dump($isLoggedIn);
});

Undefined property: mako\application\Web::$gatekeeper

**Comment by ConsoleTVs** [comment]
CURRENT CODE:

<?php

use mako\auth\gatekeeper;


$filters->register('auth.check_login', function(gatekeeper $gatekeeper)
{
	if($gatekeeper->isLoggedIn() == false){
		echo "NOT LOGGED IN";
		die();
	}
});

WORKING but leads to Not Logged In Error althought i logged in, checking codes....

**Comment by ConsoleTVs** [comment]
OKE WORKING - I thought that: $successful = $this->gatekeeper->login($email, $password);

already saved a session, so in fact i sall save the session myself!

Thanks!

Maybe future feature? set session when login with gatekeeper?
