### ISSUE TITLE
Login session not working?

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#135]
LOGIN:
http://puu.sh/fhQiD/a1dff53d11.png

LOGOUT & LOGIN FORM:
http://puu.sh/fhQ3T/904f0e5a26.png

**Comment by ConsoleTVs** [comment]
Seems like it say That I logged in successfully but after I visit any other page, and check if it is logged it, he's not, meaning that the session does not pass or something?

**Comment by ConsoleTVs** [comment]
Manually it works lol

public function testLogin(ViewFactory $view)
    {
        $this->gatekeeper->login('loginUser@gmail.com', 'pass');
        return "LOGGED IN";
    }

    public function testCheck(ViewFactory $view)
    {
        $isLoggedIn = $this->gatekeeper->isLoggedIn();
        return $isLoggedIn;
    }

**Comment by ConsoleTVs** [comment]
Seems to be solved somehow, I will close it later once I got it all working!

**Comment by letr0n** [comment]
Pretty sure it's because you call ```die```. This halts all execution and the cookie is never sent to the browser and the session isn't written to the store.

**Comment by ConsoleTVs** [comment]
Working now thanks!
