### ISSUE TITLE
[No Issue] - Noxen 2.0 Mako's Administration Panel

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#136]
http://forum.makoframework.com/discussion/340/preview-noxen-2-0-makos-administration-panel

Hello, I'm the developer of Noxen, I would like to keep in touch with mako's creator if that's possible, I want to ask some things, and in order not to spam github or something i will be leaving my skype here, so if you can please add me!

Skype: Console39

**Comment by freost** [comment]
Hi,

You can send me a PM on the forum (same username as here).
