### ISSUE TITLE
Install mako on webhosting

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#137]
Hello i uploaded all files to: http://noxen.hol.es/

But its a free server for testing how it goes, well the fact is that all the url expect for / say:

No input file specified.

Example: http://noxen.hol.es/demo

The routes are ok, and .htaccess is there...

**Comment by letr0n** [comment]
It looks like your host doesn't have ```mod_rewrite``` enabled since this works http://noxen.hol.es/index.php/demo. You can disable *clean url's* in ```app/config/application.php```.
