### ISSUE TITLE
Install mako on webhost #2

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#139]
new issue, Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/alliberantbits/www/vendor/mako/framework/src/mako/application/Web.php on line 52
I am installing it on a premium domain / hosting...

I get this error, i cannot solve it in ANY way, it is the same website as in localhost / http://noxen.hol.es/

**Comment by freost** [comment]
What version of Mako are you using and  what's the PHP version on the server?

**Comment by ConsoleTVs** [comment]
I noticed a missmatch between the required version and the server one, actualy the most up to day they got is 5.4, is it posible to downgrade my mako version?

**Comment by letr0n** [comment]
You can downgrade the Mako version by changing your ```composer.json``` file and running a ```composer update```. But you might have to do some changes to your application if it relies on newer functionality.
