### ISSUE TITLE
[RFC] Commander middleware

### ISSUE THREAD

**Issue by letr0n** [mako-framework/framework#142]
I was playing around with some stuff and came up with a simple middleware stack (decorator). I then made it possible to decorate command handlers with middleware.

You can see the implementation in this branch: https://github.com/letr0n/framework/tree/middleware
Is this something anyone would be interested to have in the core? I put the middleware class in its own namespace so it can be used in other areas of the framework core or in third party libraries as well.

Also I'm open to suggestions for names of the middleware library/class. I got inspired to name it Onion after seeing this image (http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2013/02/middleware.jpg) :stuck_out_tongue:

**Comment by telephone** [comment]
You mean I have to peel onion's in PHP now :fearful:!

As for merging into the core, I'm all for it as long as it's for the command bus and doesn't confuse users with HTTP middleware. (When one mentions middleware for PHP it's normally a reference to stackphp).

As for names, how about "Ogre"? :sunglasses:

[![Ogres are like onions](http://img.youtube.com/vi/_bMcXVe8zIs/0.jpg)](http://www.youtube.com/watch?v=_bMcXVe8zIs)

**Comment by letr0n** [comment]
Yeah I had no plans to propose that we include it for http requests since we already have filters there.

**Comment by freost** [comment]
Looks useful. Send a pull request when you're ready :+1:

**Comment by letr0n** [comment]
All right. I have some small tweaks that I want to implement so I'll probably have a pull request ready in a few hours.

I'll also open a pull request for updated docs.

**Comment by letr0n** [comment]
Pull request opened.
