### ISSUE TITLE
Class mako\auth\gatekeeper does not exist

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#146]
http://puu.sh/gdGWr/f8a9d8b9e1.png

Do you know anything that can cause this?

Gatekeeper class is there... (http://puu.sh/gdH0G/402d695606.png)

Thanks

**Comment by letr0n** [comment]
You must make sure to write Gatekeeper with a capital G in your code. It fails to load because you're on a case-sensitive filesystem.

**Comment by ConsoleTVs** [comment]
http://paste.makoframework.com/s7w

sure it's not that....

**Comment by ConsoleTVs** [comment]
News: 

Found that the problem may be in the filter, corrected capital letter, and have the following error:

http://puu.sh/gdMVS/64a0c01c09.png

The filters.php is this: http://paste.makoframework.com/s7x

**Comment by letr0n** [comment]
When you're not injecting your dependecies and use the container aware trait then you'll have to use lower case.

You can see a complete list of all typehints and keys here http://makoframework.com/docs/4.4/getting-started:dependency-injection#services :)

**Comment by ConsoleTVs** [comment]
Thanks, working now
