### ISSUE TITLE
Main Mako Website

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#147]
Hello i am a materializecss helper, and i found your site a long time ago, well the fact is that i see some things can be improved in order to make the website better, for example;

Original Version: http://puu.sh/gnuE9/9f359092db.jpg
My version: http://puu.sh/gnuAg/e601f4b90a.jpg

Is it simple? Yes (http://puu.sh/gnuLq/b12fad7246.jpg)
Then, why? Well, using materializecss is good, but it's best if you use all the functions it comes with, it's like, using mako only for routes, and you create your own and worst authentification system, when mako already got a secure one!

I can help you improving "a bit" the website, on small details and things, for example here: 

Original: http://puu.sh/gnuRp/75dc204c56.png
Modified: http://puu.sh/gnSpO/fe462d2383.png + http://puu.sh/gnSkc/750d4afa93.png (can be used as index - look at the right of the image)

Just tell me what do you think, personally i like the design as well of mako, but can be improved ofc :+1:

**Comment by telephone** [comment]
First off, thanks for suggesting a change :+1:.  I don't want my reply to sound too negative and put you off contributing but I don't like the changes suggested. The others might though.

Oh, and this would be better on the [forums](http://forum.makoframework.com) or the [docs repo](https://github.com/mako-framework/docs) as the issue doesn't affect the framework itself :wink:.

---

In the first comparison is there any difference other than making headers/subheaders non-bold and a slight change of the grey?

I haven't followed the material design too closely, but I prefer the bold/thicker text as that's what headers/subheaders should be...

In the second comparison, I'm unsure if you're try to get rid of the sidebar, move the sidebar to the right, or trying to turn it into a one-page app?

**Comment by ConsoleTVs** [comment]
Well, that is actually mentioned to suggest a full use of the framewoek, as materialize allows you to implement better thigs!! In the second example i think that a floating menu on the right would be best to move in the page, and materialize got events and things to do such, but in the first example its just an opinion adding the light class, as it's more clear but its up to each user's prereference :) i was just suggesting to use the full power of materialize at it has improved a lot :) 

You can try installing noxen, my project, with composer, try this:

composer create-project mako/noxen:2.* project-name

I used mako + materialize to create a nice CMS ( http://noxen.net )
