### ISSUE TITLE
Str::slug() does not handle special characters.

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#148]
The slug method keeps special characters in the set, rather than replacing them by a url-safe equivalent.

Expected behavior:

```php
Str::slug("Azië"); // Return azie
```

Observed behavior:
```php
Str::slug("Azië"); // Return azië
```

This could be circumvented by running it through `Str::ascii` of course, but it would be nice to have it by default.

This ticket is for Mako Framework 4.4, tested on PHP 5.6 on Ubuntu 14.10 64bit (Locale: nl_NL.UTF-8)

**Comment by letr0n** [comment]
Don't all modern browsers support UTF-8 in URLs? 

Wikipedia for example doesn't seem to be transliterating characters in their URLs (e.g. http://zh.wikipedia.org/wiki/最終幻想系列).

**Comment by freost** [comment]
You can use non-ascii characters in URIs but I see that [RFC-3986](http://www.rfc-archive.org/getrfc.php?rfc=3986) recommends using percent-encoding (that's what Wikipedia does).

I'll update the method so that all non-ascii characters get encoded.

**Comment by bertptrs** [comment]
I would recommend the following:
```php
iconv("UTF-8", "ASCII//TRANSLITERATE", $string);
``` 
That way the original meaning is conserved.
