### ISSUE TITLE
Validator (csrf) in route filter

### ISSUE THREAD

**Issue by ConsoleTVs** [mako-framework/framework#149]
Hello, is something like this posible?

http://paste.makoframework.com/sek

It throws error:

RuntimeException ( 0 )

mako\syringe\Container: Unable to resolve the [ $input ] parameter of [ mako\validator\Validator::__construct ].

**Comment by letr0n** [comment]
Hi,

Something like this should work (I haven't tested it).

```php
<?php

namespace app\routing\filters;

use mako\http\Request;
use mako\validator\ValidatorFactory;

$filters->register('csrf', function(Request $request, ValidatorFactory $validator)
{
    $rules = 
    [
        'token' => ['required', 'token'],
    ];

    $validator = $validator->create($request->data(), $rules);
    
    if($validator->isInvalid($errors))
    {
        var_dump($errors);
    }
});
```

Btw github is only for feature requests and bug reports. Please use the forums for support :)

**Comment by ConsoleTVs** [comment]
First of all thanks!, worked fine, and regarding to comunity, i'll keep it in mind, but there are few people helping there, not like you that seem to answer all my problems!
One last thing, is it posible to pass any created variables in the filter, to the controller?
the only way i can think of is with a session, what do you thing?

**Comment by freost** [comment]
You could use session flash data or create a "registry" service that you can use to pass variables around.
