### ISSUE TITLE
mod_rewrite and hide index.php from url

### ISSUE THREAD

**Issue by rafalmasiarek** [mako-framework/framework#150]
I have a problem with clear url. if i want to get to Route, for example, /hello-world I am forced to enter the address xyz.com/index.php/hello-world

This .htacces can easily improve this "feature" and hide index.php from url:
http://paste.makoframework.com/sg3

**Comment by telephone** [comment]
Check the docs for an Apache VirtualHost config: [Apache config](https://github.com/mako-framework/docs/blob/de45c5fae11f9da3818dfb3d888e9e0c61abb0f6/01_getting_started/01_installation.md#apache)

**Comment by altsniffer** [comment]
Threre's already a .htaccess file in your public folder, maybe it was not copied correctly.

**Comment by freost** [comment]
The `.htaccess` file is already included :) https://github.com/mako-framework/app/blob/master/public/.htaccess
