### ISSUE TITLE
Generate crypto key command

### ISSUE THREAD

**Issue by telephone** [mako-framework/framework#153]
I've had an 'app.generate_key' (crypto key) command in my installs for a while, and I feel it would be beneficial to include it within the framework. (It compliments the existing 'app.generate_secret' command).

In my implementation I've added a safety feature which prompts the user upon entering the command. The warning simply states that generating a new crypto key can render existing encrypted data invalid. I've also included a '--force' option to ignore the warning (for composer post-install). 

^ I'm unsure if that's the best way to implement this within the framework, so I created an issue instead of a pull request. If you're fine with the implementation I can submit a PR (based off your GenerateSecret.php).

**Comment by freost** [comment]
Sounds like a good idea to me :+1: But it would need to be able to generate a key for a specific configuration and not just override all crypto keys.

* `app.generate_key` would generate a new key for the default config.
* `app.generate_key --configuration=foo` would generate a new key for the `foo` configuration.

**Comment by telephone** [comment]
Just a quick bump. I've been sick for the past couple of weeks, but I'll have this submitted within the next couple of days :wink:.
