### ISSUE TITLE
Routes with a file extension do not work in development mode

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#154]
When using the local development server, routes that contain a file extension result in a NotFoundException, but when used with Apache they show up fine.

Note that *none* of the path elements need to exist for this error to occur. In my configuration, I have (for legacy reasons) a route to `/contact/contact.php`. The `/contact/` dir does not exist. The route is not found, but when I remove the `.php` or even just the dot, it works.

Local configuration

* Ubuntu 14.04 desktop
* PHP 5.6
* Mako 4.5.4

Server configuration:

* Ubuntu 14.04 server
* Apache 2.4.7
* PHP 5.6

EDIT: The specific error states that the route `/contact.php` was not found, rather than the full resource.

**Comment by freost** [comment]
I'm able to reproduce this but not sure what the best way of fixing it might be. A temporary solution might be to disable "clean urls" while developing.

**Comment by freost** [comment]
Fixed in 4.5.5 :)
