### ISSUE TITLE
User management commands

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#155]
In all of my projects, one of the first things I do is copy the gatekeeper user management commands I created for the last and configure them. I could add them to the current mix.

My current implementations are expired by the linux commands that do the same, so I have

* app.useradd
* app.passwd
* app.userdel

I never used groups, but I suppose they could be created as well. I'm writing this issue because I wondered the same as #153 about whether I should do a pull request immediately. It seems to me at least functionality that the authentication framework could offer.

**Comment by telephone** [comment]
Unlike the other "app." commands, not everyone enables user management. Also, some may prefer not to have cli commands that can affect users (security concerns). In saying that though, I'd like to see this as a third party package :+1:.

For the naming conventions, I'd try to keep it similar to gatekeeper as not everyone is familiar with Linux. Here's an example:

- user::create
- user::activate
- user::password
- user::delete
- group::addUser
- group::removeUser
- etc...

You'll have to ask @freost, but I think this would be a good addition to the 'mako-framework' namespace (separate package like 'toolbar').

**Comment by freost** [comment]
I have created something like this for a couple of projects at work (only the `user.create` part). Not sure if it should be a part of the core or in a separate package.

**Comment by bertptrs** [comment]
I started working on a [package that implements this](https://github.com/SolutionWeb/gatekeeper-utils). Any feedback would be great.

**Comment by letr0n** [comment]
Looks great. I'll definitely use this in some of my projects :+1:
