### ISSUE TITLE
ORM date casting cannot handle (all) postgresql timestamp values

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#156]
PostgreSQL timestamps have microsecond precision, and so do values created by the default `now()` command. When the ORM date cast attempts to cast those, it results in

```
Fatal Error ( 1 )

Call to a member function format() on a non-object
```

This is probably because the `DateTime::createFromFormat` uses a format that does not support microsecond resolution.

Steps to reproduce:

1. Create a record in postgresql with a now() value.
2. Use ORM to retrieve that record.
3. Use ORM casting to cast that value to a DateTime.

Occurs in:
Mako 4.5.5
Ubuntu 14.04 server
PHP 5.5.9
Apache 2.4.7
Postgres 9.3.9

**Comment by freost** [comment]
Whats the data type of the date column? We're using Postgres at work and I have never had any issues with date casting (we use the `TIMESTAMP` data type).

**Comment by bertptrs** [comment]
I'm using the TIMESTAMP datatype, without argument. [According to the docs](http://www.postgresql.org/docs/9.1/static/datatype-datetime.html), this is equivalent to TIMESTAMP(6).

**Comment by freost** [comment]
Sorry for taking so long to reply. I have been away for a few days and there wasn't any internet there.

Yeah thats an issue when using Postgres timestamps. Doctrine has the same problem and they also recommend using ```TIMESTAMP(0) WITHOUT TIME ZONE``` for storing dates.

**Comment by freost** [comment]
It is now possible to override the connection class and query compiler in Mako 5.
