### ISSUE TITLE
SQLite and WHERE IN subqueries go wrong

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#157]
Using the query builder and sqlite, when using WHERE IN subqueries as follows:

```php
$query->table('something')
    ->in('id', function($query) {
        $query->table('something_else')
            ->select(['other_id'])
    })
    ->all();
``` 

results in the following sql being executed:

```sql
SELECT * FROM something
WHERE id IN ((SELECT other_id FROM something_else))
```

Note the double braces. Those braces cause the subquery to only return one result. Replacing the double braces with a single brace resulst in the correct behavior.

Tested on Mako 4.5.6
PHP 5.6.11
Reproducible by command using sqlite3 3.8.11 and 3.9.1 (no others to test around)
Using Ubuntu 15.10 and Gentoo

I've already located the place where the first pair of braces is added (it is in the `in` method of the query builder) but I can't seem to find the second pair. If you could point me in the right direction, I could write a patch.

**Comment by freost** [comment]
I'm guessing that the second pair of parenthesis come from this https://github.com/mako-framework/framework/blob/master/src/mako/database/query/Subquery.php#L61
