### ISSUE TITLE
Use atomic getOrElse operations for caching where supported

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#164]
I would like to begin by saying this is a nice to have, and not an active issue.

As it stands, the `getOrElse` method for caches is not atomic, and can potentially cause a cache stampede. Some of the cache stores (at least APCU and file) could implement an atomic operation through their locking systems to avoid this.

While this is definitely not a high priority issue, it might be interesting to implement this now PHP 7 has come around with the [`apcu_entry`](https://secure.php.net/manual/en/function.apcu-entry.php) method which basically does this. For the file cache type, you could simply use exclusive and shared file locks.

However, to do this, the StoreInterface would have to change to support this method. Perhaps there could be an extended interface for caches that support this. Maybe PHP 7 added this for other caches  that I am not aware of.

**Comment by letr0n** [comment]
:+1: 

I don't think changing the interface for Mako 5 would be a problem since it's a major version (even if @freost is trying to keep bc-breaks to a minimum).

**Comment by freost** [comment]
Sound like a good idea to me. I'll add it for version 5.

**Comment by freost** [comment]
Fixed by c7fc441feb00dc9e961b49a6d1a414f65b8edc65
