### ISSUE TITLE
Using the 'apc' cache provider crashes the system when unavailable

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#167]
When the application uses the `apc` cache provider when it is unavailable, it crashes the application with a blank screen. This originally happened to me because on Arch linux, `apc` is disabled by default for the cli, even when it is enabled.

# System
Arch Linux 64 bit
Mako 4.5.4
PHP 7.0.2
php-apc installed and enabled, with the following configuration

```
extension=apcu.so
; install php-apcu-bc and enable apc.so for APC compatibility
;extension=apc.so
```
This, with the exception of uncommenting the first line, is the vanilla configuration.

# To reproduce

Have an installation as described above (or something equivalent, only php configuration is relevant) and attempt to use the apc cache using the mako Cache. Then view a page that uses it.

The result is a blank page with HTTP 200.

## Workaround

Make sure that the apc is actually enabled before using it. On arch, this means using 'apcu' or enabling the apc backwards compatibility in the configuration. However, some sort of error message would be nice.

**Comment by bertptrs** [comment]
Slight update: this was caused by a confusion between `apc` and `apcu`.

**Comment by letr0n** [comment]
This sounds more like a configuration issue than a framework bug to me.

**Comment by bertptrs** [comment]
It seems to me a bit of both. While it is indeed a configuration error to use APC when you really mean to use APCU, it seems weird to me that the framework crashes with an empty response rather than a somewhat meaningful error message.

**Comment by freost** [comment]
Cache will now throw an exception if the stores are unavailable.
