### ISSUE TITLE
Mako 3.6: redirects without full protocol are sent to HTTP

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#168]
When using `$this->response->redirect()` in Mako 3.6 without specifying a protocol, the request is sent to http instead of the protocol in use.

Mako version: 3.6.7 and earlier.

Reproduce (in a situtation where secure is true):
```php
<?php
// File: app/controllers/index.php

<?php

namespace app\controllers;

use \mako\View;

class Index extends \mako\Controller
{
        public function action_index()
        {
             return \mako\URL::to("here");
        }
}
```

Results in (something like) `http://localhost:8000/index.php/here`. This is on a fairly default installation, but with isSecure overridden to return true.

**Comment by letr0n** [comment]
Doesn't this bug also affect Mako 4.0+ as well? The check is same there as well.

**Comment by bertptrs** [comment]
So it does. I will create another pull request for that one as well then.

Hadn't noticed it yet on my Mako 4.5 sites.

**Comment by bertptrs** [comment]
Turned out to be a configuration issue and miscommunication with a fellow developer. Closing.
