### ISSUE TITLE
Blade Template Engine

### ISSUE THREAD

**Issue by MehmetNuri** [mako-framework/framework#175]
Blade template engine support will be provided ?

**Comment by aldoanizio** [comment]
Hi there.

I think you can use another template engine using a custom view renderer. Take a look at documentation:

http://makoframework.com/docs/4.5/learn-more:views#custom_view_renderers

You may need to implement the renderer to make the 'bridge' between mako view structure and Blade.

**Comment by MehmetNuri** [comment]
Thank you so much :)
