### ISSUE TITLE
Spelling mistake in a framework.

### ISSUE THREAD

**Issue by Justin991q** [mako-framework/framework#176]
Since you're a framework and you want to be professional, you might wanna correct this spelling mistake in one of your functions.

Connection::queryAndCoun**d** should be Connection::queryAndCoun**t**

It's confusing. ;)

**Comment by letr0n** [comment]
Which version are you using? I was going to make a pull request but I can't find a misspelled version

M5: https://github.com/mako-framework/framework/blob/master/src/mako/database/connections/Connection.php#L532
M4.5: https://github.com/mako-framework/framework/blob/4.5/src/mako/database/Connection.php#L562
M4.4: https://github.com/mako-framework/framework/blob/4.4/src/mako/database/Connection.php#L525
M4.3: https://github.com/mako-framework/framework/blob/4.3/src/mako/database/Connection.php#L525
M4.2: https://github.com/mako-framework/framework/blob/4.2/src/mako/database/Connection.php#L525
M4.1: https://github.com/mako-framework/framework/blob/4.1/src/mako/database/Connection.php#L525
M4.0: https://github.com/mako-framework/framework/blob/4.0/src/mako/database/Connection.php#L345

**Comment by freost** [comment]
Fixed 😉
