### ISSUE TITLE
Child templates extend Parent templates.

### ISSUE THREAD

**Issue by colcrunch** [mako-framework/framework#181]
I have decided to take a dive into PHP frameworks, and decided to try out [Mako Framework][1] after looking through the docs and getting a feel for what it offered. 

Sadly, I have hit a bit of a snag that the docs don't really help me with. If you scroll up a little on [this][2] page, you will see the section that talks about parent and child templates. 

Here is the code I have thus far:

Admin Controller:

    <?php
    namespace app\controllers;

    use mako\http\routing\Controller;
    use mako\view\ViewFactory;

    class Admin extends Controller
    {

    public function login(ViewFactory $view)
    {
    return $view->create('login');
    }

    }

partials/adminHead.tpl.php:
    
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="{{$__charset__}}">
        <title>{{block:title}}{{endblock}}</title>
        <link rel="stylesheet" type="text/css" href="../assets/css/materialize.css"  />
        <script src="../assets/js/materialize.js"> </script>
    </head>

login.tpl.php:

    {% extends:'partials.adminHead' %}
    {% block:title %} Admin Login - My Blog{% endblock %}

    <body>
     <nav>
       <div class="nav-wrapper">
          <div class="col s12" style="margin-left: 20px;">
            <a href="#!" class="brand-logo">Logo</a>
            <ul class="right hide-on-med-and-down" style="margin-ri: 20px">
             <li><a href="sass.html">Sass</a></li>
              <li><a href="badges.html">Components</a></li>
              <li><a href="collapsible.html">JavaScript</a></li>
            </ul>
         </div>
       </div>
     </nav>

The result that I get is `{% extends:'partials.adminHead' %}` printed out above the rendered HTML, instead of what the docs claim.

In case my description of the output was not clear, here is a picture:

[![Output][3]][3]

EDIT: The `{% block:title %}` and `{% endblock %}` is not being printed when I remove the extends statement.

  [1]: http://makoframework.com/
  [2]: http://makoframework.com/docs/4.5/learn-more:views#custom_view_renderers
  [3]: http://i.stack.imgur.com/JIzfp.png

**Comment by letr0n** [comment]
Hi,

You'll have to make some slight changes to your views to get the desired output:

```<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="{{$__charset__}}">
    <title>{{block:title}}{{endblock}}</title>
    <link rel="stylesheet" type="text/css" href="../assets/css/materialize.css"  />
    <script src="../assets/js/materialize.js"> </script>
</head>

{{block:body}}{{endblock}}

</html>```

```{% extends:'partials.adminHead' %}

{% block:title %} Admin Login - My Blog{% endblock %}

{% block:body %}
<body>
 <nav>
   <div class="nav-wrapper">
      <div class="col s12" style="margin-left: 20px;">
        <a href="#!" class="brand-logo">Logo</a>
        <ul class="right hide-on-med-and-down" style="margin-ri: 20px">
         <li><a href="sass.html">Sass</a></li>
          <li><a href="badges.html">Components</a></li>
          <li><a href="collapsible.html">JavaScript</a></li>
        </ul>
     </div>
   </div>
 </nav>

 {% endblock %}```

**Comment by colcrunch** [comment]
doing that leaves me with a page with just `{% extends: 'partials.adminHead' %}` which leads me to believe there is something wrong with whatever logic parses that line.

**Comment by colcrunch** [comment]
Close this, it would appear composer somehow messed up on the first project. I remade the project and it now works.
