### ISSUE TITLE
4.5 still requires a too specific Monolog version

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#182]
As @TobiasKappe mentioned in #178, Mako requires a too old version of monolog, causing trouble for projects using newer versions.

The mentioned pull request has been checked into master, but it is not available for the 4.5 branch.

Could the monolog requirement for the framework be changed to `^1.13.1` for the 4.5 release as well?

Thanks

**Comment by freost** [comment]
Fixed in 4.5.11 :)
