### ISSUE TITLE
OpenSSL Encrypter is vulnerable to Chosen-Ciphertext Attacks

### ISSUE THREAD

**Issue by paragonie-scott** [mako-framework/framework#183]
https://github.com/mako-framework/framework/blob/4bf7386aead7d65b8d34d5b45874e566b02eb449/src/mako/security/crypto/encrypters/OpenSSL.php

You're not applying a MAC over the IV and ciphertext and validating it before attempting decryption.

(OFB isn't an AEAD mode, and AEAD modes are only supported by PHP in 7.1.0 and newer, which isn't out yet.)

**Comment by letr0n** [comment]
It can be done using the [encryptAndSign](https://github.com/mako-framework/framework/blob/master/src/mako/security/crypto/Crypto.php#L92) method but I agree that it should be done by default and not be optional.

**Comment by paragonie-scott** [comment]
Also: using `substr()` on ciphertext + mbstring.func_overload can lead to invalid results.

Recommendations:

* https://github.com/paragonie/constant_time_encoding - Look at `Binary`
* https://github.com/defuse/php-encryption - Does authenticated encryption correctly

**Comment by freost** [comment]
Thanks to both of you :)
