### ISSUE TITLE
Error handling on PHP 7 leads to empty response

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#187]
Starting PHP 7, (most) internal errors result in an `Error` being thrown, rather than the error handler being called. This is caught by the framework, which passes it to the error handlers. Unfortunately, those expect an `Exception`, not an `Error`, which results in another `Error`.

This continues recursively until PHP runs out of stack space, after which it promptly returns an empty response, which makes debugging a little hard (took me months to figure out this was happening).

Affected Mako versions:

- Mako 3.5 (Any version). Somewhat fixed by https://github.com/DeLeidscheFlesch/Mako/commit/3503afef29df7df5fcd4f183eac505e900df86b9
- Mako 4.5 (Any version)

PHP: version 7.0.9, but any 7+ version should have this behaviour.

**Comment by letr0n** [comment]
You can create your own ErroHandlerService where you replace ```\Exception``` with ```\Throwable``` https://github.com/mako-framework/framework/blob/4.5/src/mako/application/services/web/ErrorHandlerService.php#L47 and just update your ```application.php``` config file to use that instead of the default service.

**Comment by bertptrs** [comment]
I agree that rolling my own error handler would solve this, but that is a lot of duplication for something that is an issue for anyone running PHP 7.

Currently, I use the following workaround, converting the Error to an ErrorException:
```php
// File: src/mako/error/ErrorHandler.php

// SNIP
    public function handler($exception)
	{
        if ($exception instanceof \Error) {
            $exception = new \ErrorException($exception->getMessage(), $exception->getCode(), 0, $exception->getFile(), $exception->getLine());
        }
        try {
// And so forth…
```

This makes me lose the stack trace, but it no longer results in what we started to call a "White screen of death."

**Comment by letr0n** [comment]
I don't think there is an easy way of getting an error handler that works well on both PHP7 and PHP5 because of all the typehinting. I think I'll create a package that only contains the M5 error handling code so that one can use that with a 4.5 project.

**Comment by letr0n** [comment]
All right here it is https://github.com/letr0n/error-compat :)
