### ISSUE TITLE
PHPDoc for CacheManager::instance is incorrect

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#188]
The CacheManager::instance PHPDoc states that it will return a `mako\cache\stores\StoreInterface`, which does not define a `getOrElse` method, but it actually returns a `mako\cache\Cache`, which does.

I unfortunately figured this out after spending a bit too munch time wondering why my unit test mock refused to overload the `getOrElse` method.

Affected Mako versions: 4.5.x
PHP version: PHP >= 5.5

**Comment by freost** [comment]
Fixed in 4.5.14 👍
