### ISSUE TITLE
Extra newlines in console commands

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#192]
When creating and using a console command, one empty line is printed before command execution and one empty line is printed afterwards.

This makes these commands not easy to use with services like `cron`, which will email any output (if present) to the owner of the cronjob. For services that do not produce output, the `--mute` flag does work, but for commands that output errors when they encounter them, this is rather inconvenient, as the error output does need to be emailed.

Can these additional newlines be removed or at least made optional?

This issue applies to pretty much any Mako Framework version available in this repository.

**Comment by letr0n** [comment]
Looks like they have been removed in Mako 5

**Comment by bertptrs** [comment]
Thank you. I've spent the day attempting to upgrade, but the lack of documentation surrounding the upgrade path has been a bit of a problem. I'll send a pull request to the documentation when I'm done.

However, as long as #193 is in the code, I cannot use it for production yet. For now, I'll work around it with a pipe to `tail` and `head`.

**Comment by bertptrs** [comment]
Well, after spending about a day and a half on porting the entire project to version 5.0. Aside from #193, it was fairly easy to do (and along the way increased the test coverage as well while I was debugging some inconsistencies)

I really liked the Middleware interface as a replacement for the filters. This worked wonderfully for inherently connected before and after filters like cache read/write, which could now be consolidated.

If everything is not on fire next week, maybe I'll have time for a post-mortem. Closing this issue now as the original problem is mitigated.

**Comment by letr0n** [comment]
A post-mortem would be interesting. We have just deployed our code on M5 and everything is running smoothly.
