### ISSUE TITLE
Suggestion: add code style configuration and checkers

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#197]
Since Mako has a somewhat non-standard code style (almost PSR-2 but not quite) pull requests (including my own) don't always follow them to the letter, requiring cleanup commits.

This can be avoided while improving code quality, by adding some checking mechanism. Tools like [GrumPHP](https://github.com/phpro/grumphp) (for enforcing checks on commit) and [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) (for verifying and automatically correcting codestyle) can help with this.

Would you be interested in adding this to the project (in require-dev of course)? I could write a preliminary configuration to start with.

**Comment by letr0n** [comment]
We have a git-hook repo with a very basic php-cs-fixer setup ([mako-framework/git-hooks](https://github.com/mako-framework/git-hooks)). Maybe it could be extended?

**Comment by freost** [comment]
It would be great to have code-style checking. I have thought about it multiple times but I haven't had time to work on it.
