### ISSUE TITLE
CLI handler has incorrect return type specification

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#199]
In the CLI error handler (`mako\error\handlers\CLIHandler`) the following function exists:

```php
        /**
         * Retruns a generic error.
         *
         * @access  protected
         * @return  string
         */
        protected function getGenericError(): string
        {
                $this->output->errorLn('<bg_red><white>An error has occurred while processing your task.</white></bg_red>' . PHP_EOL);
        }
```

Aside from the typo in the docblock, the function does not actually return anything, thus crashing the system while it is handling the error. As the function result is not actually used, I recommend removing the return type declaration altogether.

Affects Mako 5, any platform.

**Comment by freost** [comment]
Fixed in 5.0.19 👍
