### ISSUE TITLE
Suggestion: set exit status for console commands

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#200]
Currently, when you execute a console command, its exit status is successful on a normal exit (no uncaught exceptions) and failure on abnormal exit. It would be nice however to be able to mark an execution as failed, without throwing an exception and spamming the log files.

This way, the console commands can be of more use in conditional shell scripts and as services in an automated system.

This could work as follows: we cast the return value from the `execute` method of a console command to an integer, and set that as our return status. This is backwards compatible (`null` casts to `0`, which is a succesful exit) and allows for this feature to return any desired exit status.

I'd like to know what you think.

**Comment by freost** [comment]
Sure I wouldn't be opposed to adding this feature.

Two solutions popped into my mind when I read the issue. The first was to have a method called `setStatus` or just `status` (same as the method name used for HTTP responses) that you could call anywhere in the console command.  The second was as you suggested just to return the status code directly from the `execute` method.

**Comment by letr0n** [comment]
Just returning the status code would probably be the best solution.

**Comment by freost** [comment]
You can now return the exit code in 5.0.21
