### ISSUE TITLE
Logout gatekeeper problem

### ISSUE THREAD

**Issue by sorxrob** [mako-framework/framework#201]
I made a simple authentication with my mako-framework project. Everything works fine though I am experiencing an issue.

In my AuthController.php, I have this:
```
    public function logout()
    {
        $this->gatekeeper->logout();
        return $this->redirectResponse('/');
    }
```
This works though when I click the back button of my browser, it still shows the previous state instead of redirecting to the login page since I have a `beforeAction` function in my controllers. I have to refresh the page for it to redirect to the login page.

Is this a browser issue? A session issue or a caching issue? Any help would be much appreciated.

**Comment by letr0n** [comment]
The session id is regenerated and the auth token is deleted when the `Gatekeeper::logout()` method is called. So it's just your browser cache :)

**Comment by sorxrob** [comment]
Oh so that's not a problem at all then 👍 Thank you! Merry Christmas!!!! Very nice framework for my project.

**Comment by letr0n** [comment]
No problem. Merry Christmas to you too 🎅
