### ISSUE TITLE
whereRAW is not working. Date counted as a string

### ISSUE THREAD

**Issue by sorxrob** [mako-framework/framework#203]
So in my table, I have a field created_at which have values like `2016-12-30 00:30:10` and I query it using query builder by:

```
$now = date('Y-m-d');
->where('Date(created_at)', '=', $now)
```

because I want to get data only with date = today.

It returns an error `Unknown column 'Date(created_at)'` most probably because the framework is sending that parameter in quotes. So I tried the raw query option

```
$now = date('Y-m-d');
->whereRaw('Date(created_at)', '=', $now)
```

And I got the same error. 

Any fix for this? Thank you!

**Comment by letr0n** [comment]
`whereRaw` works the other way. It expects the third parameter to be raw SQL instead of a bound parameter.

You can achieve what you want to do like this:

```php
$now = date('Y-m-d');

->where(new Raw('Date(created_at)'), '=', $now)
```

Just remember to import `mako\database\query\Raw`

**Comment by sorxrob** [comment]
Good day!

Tried out the code and it worked. Thank you!
