### ISSUE TITLE
Missing details in documentation

### ISSUE THREAD

**Issue by blindpenguin** [mako-framework/framework#205]
Hi,

there are some parts in the documentation where i have no idea what i'm supposed to do. Right now i'm struggling with adding an user to a group. To get the group i have to get the ID of a group and then call the add user function.

According to the documentation finding a group works like this:

`$group = $groupProvider->getById($id);`

So, where does the "$groupProvider" come from?

Thanks.

**Comment by letr0n** [comment]
It comes from ```$this->gatekeeper->getGroupProvider();``` Its documented at the end of the ```Basic usage``` section :)

**Comment by blindpenguin** [comment]
Ah, didn't see. Sorry.

Another thing i can't seem to find is the pagination stuff. Where  does the "$pages", "$previous", etc. variables come from in the example?

https://makoframework.com/docs/5.0/learn-more:pagination#pagination_rendering_example_view

**Comment by letr0n** [comment]
They automatically get assigned to the view by the ```render``` method of the paginator.

**Comment by blindpenguin** [comment]
Ok, apparently the render method needs to be echoed out. In this case i'm sure i couldn't find it anywhere in the docs. :D But now i have pure PHP inside of a template...

Btw. there is a typo. The title says "Pagination redering".

**Comment by letr0n** [comment]
You can echo the pagination template using the ```{{raw:$pagination->render()}}``` syntax.
