### ISSUE TITLE
Run app inside www folder

### ISSUE THREAD

**Issue by sorxrob** [mako-framework/framework#208]
So I am currently running makoframework via root folder `php- S localhost:8000 -t public`. 

What if I want to put it inside www folder of wamp? So I can access it for example by `localhost/mako-app`? Would that be possible? I tried and the routes and assets are not working proplery. 

What's the best way to do this?

**Comment by letr0n** [comment]
Never used WAMP but you should just be able to drop your app in the `www` directory and visit it from `http://localhost/app-name/public/index.php`.

**Comment by sorxrob** [comment]
@letr0n I just said that if you directly put it in www and access it by that the routes and assets will not work properly

**Comment by letr0n** [comment]
"Not working properly" isn't very helpful. What kind of errors are you getting?

**Comment by sorxrob** [comment]
Okay let's say I am in the h`ttp://localhost/app/public/` which displays perfectly fine, but when I tried to login for example instead of going to `http://localhost/app/public/login` it goes to `http://localhost/login`

**Comment by letr0n** [comment]
How are you building your URLs? The ideal way is to use reverse routing (https://makoframework.com/docs/5.1/routing-and-controllers:routing#reverse_routing).
