### ISSUE TITLE
Feature request: Add redirect routes to the routing system

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#209]
In my application, I have a lot of routes that used to exist and no longer do so. (2005 was a fun time) As such, those routes need to redirect to their replacements for both compatibility and SEO.

Currently, this is slightly tedious because for every route I want to redirect, I need a controller action, or implement a closure that fiddles with a `Response` object. This is a little overkill for things that really aren't all that complicated.

Instead, wouldn't it be nice to have a function like this

```php
class Routes {
    // … snip …
    function redirect(string $route, string $redirect, int $status = 307) {
        // Some implementation
    }
}
```

Which we then could use like

```php
$routes->redirect('/old/{foo}/{bar}/', '/new/$bar/$foo/', 301);
```

in our routing files. It would be even better if we could support named routes as the destination, so that if a named route exists with the given pattern and parameters, we redirect to that, like so:

```php
$routes->get('/new/{foo}/', function (){return 'bar';}, 'baz');
$routes->redirect('/old/{foo}/', 'baz', 301);
```

If you support this idea, I could provide a patch, as my employer would like to see this feature.

**Comment by letr0n** [comment]
We have a lot of routes that we're redirecting as well (some of the routes are 15 years old). One solution that I think would work pretty well is if the `Routes` class used the `ExtendableTrait`. This would make it super easy to add custom routing functionality that fit our needs.

**Comment by bertptrs** [comment]
While also acceptable, this is rather basic functionality so I think I would prefer the framework itself offering some form of support for this. But I don't know your requirements, maybe we could work that into this as well.

**Comment by letr0n** [comment]
We do some logging for some of the redirect routes and add additional headers for others. So I'm not sure if it's possible to create a "one size fits all" solution.

**Comment by freost** [comment]
I'm leaning towards using the `ExtendableTrait` for this. Any other classes that might benefit from using it?

**Comment by bertptrs** [comment]
Maybe the `Config` class, to support for example database-stored configuration values? But I have not read that much into the ExtendableTrait, in fact, I did not know it existed until now.

Still, it seems a bit hackish to bolt it on that way, as redirects are currently a native feature of controllers. Adding it to routing seems logical to me.
