### ISSUE TITLE
$response->header('XXX') converts headers to lowercase

### ISSUE THREAD

**Issue by mblarsen** [mako-framework/framework#210]
The header function converts header keys to lowercase. It shouldn't. E.g.

```
$response->header('XXX', 'YYY');
```

turns into:

```
xxx: YYY
```

not:

```
XXX: YYY
```

**Comment by letr0n** [comment]
Hi, header field names are case-insensitive according to the spec so it shouldn't really matter https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by sharifzadesina** [comment]
@letr0n sometimes it matters, it is better to work like PSR-7 headers.

**Comment by mblarsen** [comment]
@letr0n thanks for the link.

I guess the correct way for client libs is to do a transform in their header getter. In chrome if you do `getgetResponseHeader('xXx')` it correctly retrieves the header. But `getAllResponseHeaders()` returns headers as is (which is okay I guess). 

That said it think that since it doesn't matter what case it is, that it is excluding all the libs that don't do a case insensitive check.

**Comment by freost** [comment]
I have made some changes so headers will be sent using the case that they were defined with in the next version (5.2) :)
