### ISSUE TITLE
[5.1] Undefined variable: i18n

### ISSUE THREAD

**Issue by SkyzohKey** [mako-framework/framework#212]
Hey guys, thanks for the awesome work you put for us.

Anyway I'm getting a weird error with i18n, when doing the following everything works as expected
```php
public function welcome(ViewFactory $view): string
{
	return $this->i18n->get('ui.services.sleep-apnea');
}
```

But when I try to load a view that contains i18n template tags, the `Undefined variable: i18n` message is displayed (error page).

```
public function welcome(ViewFactory $view): string
{
	return $view->render('welcome');
}
```
```php
<meta name="description" content="{{$i18n->get('ui.meta.description')}}">
```

This one fails with the following error:
```
Notice ( 8 )
Undefined variable: i18n
```

**Comment by letr0n** [comment]
Hi,

You have to assign i18n to the view.

```php
return $view->render('welcome', ['i18n' => $this->i18n]);
```

You can also assign it globally to all views like this (can also be done in the bootstrap.php file)

```php
$this->view->assign('i18n', $this->i18n);
```

**Comment by SkyzohKey** [comment]
Oh, nice, thanks. Before closing this issue just another quick question:
My app works like a charm on local, but once I deploy it, only the `/` route works, every other routes don't. I'm obliged to use `/index.php/page`. But for some reason i ignore, even with the `clean_url` property set to `true` it doesn't work. Any idea ?

**Comment by letr0n** [comment]
The included .htaccess file has always worked for me. What does the `RewriteBase` directive do? Been a while since last time I used Apache.

**Comment by SkyzohKey** [comment]
Yep, fixed the issue by adding a `?` like that : `index.php?/$1`. 😂😂
