### ISSUE TITLE
--env option on CLI is ignored

### ISSUE THREAD

**Issue by ossigeno** [mako-framework/framework#213]
e.g. 
php reactor expiring_jobs --env=dev

env is still the default

**Comment by freost** [comment]
Which version are you using? It works for me:

```php
public function execute()
{
    $this->write($this->app->getEnvironment());
}
```

```
php app/reactor test --env=foo
foo
```

**Comment by ossigeno** [comment]
5.1.3

$this->app->getEnvironment() returns correct env but any $this->config->get() request is going to the default config.

**Comment by freost** [comment]
Ah yes. If the config file has been loaded before the environment gets set internally then it won't reload it from disk. This will always happen to the `application.php` config file and any config file loaded in `bootstrap.php`.
