### ISSUE TITLE
Question: Where is urlBuilder in view?

### ISSUE THREAD

**Issue by zztv1** [mako-framework/framework#214]
Where is it?

**Comment by aldoanizio** [comment]
You should pass it as a global variable.

Something like this: $this->view->assign('urlBuilder', $this->urlBuilder);

I particularly like to create a base controller and inject all elementary services (urlBuilder, config, i18n) as a global variable in View.

I think if you can use bootstrap.php file as well.

**Comment by zztv1** [comment]
Like so?

```php
#bootstrap.php
<?php

$view = $container->get('view');

$view->assign('i18n', $container->get('i18n'));
$view->assign('urlBuilder', $container->get('urlBuilder'));

```
