### ISSUE TITLE
Bypass view caching for a div

### ISSUE THREAD

**Issue by SkyzohKey** [mako-framework/framework#216]
Hey guys,

Is it possible to bypass the view cache only for an element inside of the view (opening hours of a medical institute).

This is an information that changes periodically and it needs to be reflected in real time, so the user has to refresh even if they just loaded the page to see the real status (Open/closed).

Here is the website: https://drmelin.be/en

Thanks in advance guys 😎

**Comment by freost** [comment]
The only way to achieve that would be to send in the dynamic data from the controller.
