### ISSUE TITLE
database one master many slave

### ISSUE THREAD

**Issue by lhfeng** [mako-framework/framework#218]
hello:

how to config database connections one master many slave.

eg : "test" db, one master to write , three slave to read. read connection can be random。

Hope reply。

**Comment by freost** [comment]
Hi,

The framework itself doesn't have any read/write split features as I think this is something that it better handled by other means.

If you're using MySQL then you can have a look at [mysqlnd_ms](http://be2.php.net/manual/en/book.mysqlnd-ms.php) (there's a simple setup guide [here](https://blog.engineyard.com/2014/easy-read-write-splitting-php-mysqlnd)). Similar solutions exist for other databases as well.

**Comment by lhfeng** [comment]
ok , i got it, thanks.
