### ISSUE TITLE
redirect in routing middleware?

### ISSUE THREAD

**Issue by altsniffer** [mako-framework/framework#222]
Hi

Is there a way to redirect user within the routing middleware?

**Comment by freost** [comment]
Yes. Just set the response body to an instance of `mako\http\response\senders\Response` :)

**Comment by altsniffer** [comment]
Hi thanks for anwser :)

Do you have an example? 
I'm using gatekeeper to check if isGuest(), this works but im not sure about the redirect :D
I can't find `mako\http\response\senders\Response`
