### ISSUE TITLE
Gatekeeper interfaces missing method declarations since 5.2

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#223]
Since the move from `mako\auth\Gatekeeper` to `mako\gatekeeper\Authentication`, most related interfaces are missing most of the method declarations, as specified in [the documentation](https://makoframework.com/docs/5.2/security:authentication). Most notably, all mention of group repositories is missing. Because all of this is missing, IDE support is pretty much impossible.

If this is deliberate (to not force implementors to implement everything) would you consider adding them anyway and introducing some sort of `NotImplementedException` to be thrown in those cases? That way you can have some abstract base for everything that just throws that exception for everything, so you still don't burdon implementors with creating every method, but still allow for a complete interface specifying all methods involved.

**Comment by freost** [comment]
This can be solved by using comments in PhpStorm and NetBeans (and probably others):

```/* @var $adapter \mako\gatekeeper\adapters\Session */```

![phpstorm](http://i.imgur.com/7UPe7pC.png)

**Comment by bertptrs** [comment]
That works around this issue, thanks.
