### ISSUE TITLE
Default error views cannot be overwritten

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#224]
The default Mako web error handler renders the view `mako-error::$code` when an exception occurs, causing a view lookup in the `mako-error` namespace.

It is possible to declare namespaces of your own, but since the `mako-error` namespace is declared in the namespace of the `WebHandler`, which is only called just before the error is handled. Because of this, it always overrides whatever namespace you have declared there for yourself.

This way, overriding the default views needs to be done by either

- adding your own views in the Mako framework directory, which is a bad idea, or
- rolling your own error handler, which is just silly code duplication.

A possible solution would be to register the namespace in the `ErrorHandlerService`, which is registered after the views by default so this wouldn't be a problem.

**Comment by freost** [comment]
Maybe I'm misunderstanding something but adding `packages/mako-error/404.tpl.php` in the application view directory allows me to override the default 404 template with a custom one.

**Comment by bertptrs** [comment]
Confirmed, this works, so this issue can be closed. Thank you. Could you tell me where I could have found this in the documentation? Because I couldn't find anything about namespaced views.

**Comment by freost** [comment]
The feature was added in the 4.3.0 update but it looks like I forgot to document the feature. I'll add it to my todo list.
