### ISSUE TITLE
Error logging does not work when default handler is not used

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#225]
The config setting `application.error_handler.log_errors` can be used to automatically log errors when they happen, but it does not work when the default error handler is not called.

This is because the logger on the ErrorHandler is set only in the `handle` closusure in `ErrorHandleService::register` which isn't called until the error handler is called. When that never happens, the logger is not registered so the error handler does not log.

Due to #224, it is rather necessary to have a custom error handler that outputs an error page, thus leading to this issue.

A current workaround is to call `ErrorHandler::setLogger` in your own error custom error handlers, but that is rather inconvenient.

**Comment by freost** [comment]
Fixed in 5.2.9. Sorry for taking so long to fix this.
