### ISSUE TITLE
Validation with parameters is broken

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#227]
If you use validation plugins with parameters (as stated [in the documentation](https://makoframework.com/docs/5.2/learn-more:validation)) you get the following error:

> mako\validator\Validator::validate(): Call to undefined validation rule 'min_length(4)'.

This is because the documented parameter format (arguments between brackets) does not match the implemented code (JSON after a colon). The offending code is in the `Validator::parseRules` function, which calls `FunctionParserTrait::parseFunction`.

The correct way to call these plugins seems to be like this:
```php
// Does not work
$incorrectRules = [
    'foo' => ['min_length(3)', 'in:(["bar", "baz"])'],
];
// Does work
$correctRules  = [
    'foo' => ['min_length:[3]', 'in:[["bar", "baz"]]'],
];
```
which is really ugly with the repeated square brackets for array parameters, and requiring square brackets at all for just an integer.

This affects all validator plugins with parameters in Mako 5.2.

**Comment by freost** [comment]
Are you sure that you're using 5.2? We're using 5.2 and our rules look like this:

```php
$validator = $this->validator->create($params,
[
	'report'      => ['required', 'max_length(300)'],
	'report_type' => ['required', 'in(["correction","remark"])'],
	'object_ref'  => ['required'],
	'source_id'   => ['required'],
]);
```

**Comment by bertptrs** [comment]
… yeah, that was the obvious solution. Consitency across projects is hard. Sorry to bother you.
