### ISSUE TITLE
Bug: Cache Database result not working

### ISSUE THREAD

**Issue by altsniffer** [mako-framework/framework#230]
Hi

If i cache my database result, for example: News::all() it stores into a cache file but you can't work with it.
Bug or not a function in version 5? it worked with version 4
$news->headline getting 'Trying to get property of non-object'

object(__PHP_Incomplete_Class)#271 (3) { ["__PHP_Incomplete_Class_Name"]
instead of
object(mako\database\midgard\ResultSet)#229 (1) { ["items":protected]

regards

Has this something todo with the new config: deserialization_whitelist? :)

**Comment by freost** [comment]
Hi,

I think it's because of the `deserialization_whitelist` option in the `application` config file. You'll either have to list all classes you want to allow it to deserialize or just set it to `true` if you want it to be able to deserialize any class (same as in Mako 4)

**Comment by altsniffer** [comment]
That was the reason :)

Thanks have a nice day/evening
