### ISSUE TITLE
Bad Quality on Image resize

### ISSUE THREAD

**Issue by altsniffer** [mako-framework/framework#232]
Helloo

I got a really bad quality of image when using Image::resize() for thumbs.
but after change the "imagecopyresized" to "imagecopyresampled" (mako\pixl\processors\GD line: 268), much better quality. Not sure if bug or some server features :P

regards

**Comment by freost** [comment]
Hi,

What size is the original image and what size is the thumbnail (in pixels)?

**Comment by freost** [comment]
Fixed in 22ee226c9b940344fa5b0604094cbebf9ad0c75b

It will be in included in the `5.3.1` release.
