### ISSUE TITLE
Filtering by junction table?

### ISSUE THREAD

**Issue by MoonbiteAgency** [mako-framework/framework#235]
Is this possible ? 
something like:
$q->alongWith('name', function($query) {
$query->where();
})

**Comment by letr0n** [comment]
I think it should be possible using a normal `where` since the junction table is already joined in when querying `many to many` relations.

```sql
SELECT 
  `groups`.* 
FROM 
  `groups` 
  INNER JOIN `groups_users` ON `groups_users`.`group_id` = `groups`.`id` 
WHERE 
  `groups_users`.`user_id` = 1
```

**Comment by freost** [comment]
As @letr0n letr0n suggested it is already possible using a normal `where` clause.

```php
$userGroup = UserGroup::including
([
	'users' => function($query)
	{
		$query->alongWith(['role', 'hide_mobile', 'hide_email']);
		$query->where('show_as_contact', '=', 1);
	},
])->get($id);
```

The `show_as_contact` field is in the junction table.

**Comment by darekmeco** [comment]
Very nice, add this to docs please.
