### ISSUE TITLE
Eager loading of BelongsTo relations is inefficient with repeated keys

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#236]
Like the title says. When keys are often repeated, eager loading of related records is very inefficient, because an array of all keys is allocated, which is only later made "unique", as seen in [BelongsTo.php](https://github.com/mako-framework/framework/blob/5db8790dae9071081d7e96fa3d4396518fa9413c/src/mako/database/midgard/relations/BelongsTo.php#L44).

When a dataset is rather large (60K records in my own example) but has only very few unique foreign keys (about 300) this causes a very large chunk of memory to be allocated for nothing, potentially causing memory shortage.

A possible solution is to instead use the array keys instead, so repeated values are not a problem. Like so:
```php
		$keys = [];
		$foreignKey = $this->getForeignKey();
		foreach($results as $result)
		{
			$val = $result->getRawColumnValue($foreignKey);
			if ($val) $keys[$val] = null;
		}

		return array_keys($keys);
```

HasOne and HasMany relations are not affected I believe, since you have at most as many keys as you have records, and also those keys tend to be unique.

**Comment by freost** [comment]
The code above and the current code produces exactly the same memory usage (82MiB) when I'm testing (60k `Bar` records that belong to 1k different `Foo` records).

```php
$bar = Bar::including('foo')->all();

var_dump($bar->count()); // 60000

var_dump(memory_get_peak_usage(true) / (1024 ** 2)); // 82.0078125
```

Are you seeing improved results?

**Comment by letr0n** [comment]
I had a go at this too and I'm unable to reduce memory use by more than 2-3%. You probably need all the all of the records in memory simultaneously but if you don't then I would suggest using `batch` or `yield` instead of `all`.

**Comment by bertptrs** [comment]
I realise I've been silent. I've been unable to see any notable differences, and agree that this isn't helpful. We've moved to doing more work in the database to work around the memory issue anyway, so I think this can be closed.
