### ISSUE TITLE
Unable to create a [ mako\session\stores\StoreInterface ] instance.

### ISSUE THREAD

**Issue by dunsunik** [mako-framework/framework#238]
Hey,

I have just installed a default mako application. For some reason $this->session inside my controller does not work (can not be initialized).

Thank you

**Comment by freost** [comment]
Hi,

You'll have to enable the Session service by uncommenting this line https://github.com/mako-framework/app/blob/master/app/config/application.php#L115 in the `application.php` config file.

**Comment by dunsunik** [comment]
Greetings !
Ouch, I'm sorry for that stupid overlook.
Thank you
