### ISSUE TITLE
Configuration value 'application.base_url' defaults to empty string

### ISSUE THREAD

**Issue by mathysie** [mako-framework/framework#240]
###  Description
---

When the config-value of 'application.base_url' is not set, `$this->config->get(application.base_url)` returns an empty string. However, the file application.php states:
> It will be auto-detected in a web environment if left empty but should be configured if you plan to build URLs in the command line.

Thus I expect the getter to return `http://localhost:<port>` or something like that.

###  Steps to reproduce
---

Type `$this->config->get(application.base_url)` in any controller while the value of `base_url` in application.php is set to empty string and dump the results.

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.x.x                    |
| Mako Version | 5.5.5                    |
| OS           | -                        |
| Database     | -                        |

**Comment by freost** [comment]
Hi,

The comment might be a bit misleading. It's the return value of `Request::baseURL()` (also used by `UrlBuilder::base()`) that gets autodetected if you don't fill out a value in the config file.

**Comment by mathysie** [comment]
Thanks for the clarification!
