### ISSUE TITLE
Automatically run migrations in a transaction

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#242]
###  Description

For data security (and for easier recovery in the event of an error) I usually run my database migrations in a transaction. It would be nice if the framework had an option to do so by default, either as a migration propery, or a global option.

Postgres, Oracle, Sybase, DB2, SQL server and even SQLite all perfectly support rolling back structure changes, with the possible exception of creating and dropping databases. MySQL is unable to rollback, but will still accept DDL statements within a transaction, it just cannot rollback.

A possible issue is that not all database engines are overly fond of nested transactions, so this feature will need to be an option. Other than that, I don't really see any value in partially completing migrations, so this should probably be a default. Ideas?

**Comment by freost** [comment]
I'll look into it and see if there's an easy way to implement it with a graceful fallback for engines without DDL transaction support.

Would you want each batch of migrations to run in the same transaction or should each migration file be its own transaction?

**Comment by bertptrs** [comment]
I'd think that every migration file should be its own migration, since those are expected to be atomic (fail or not) but an entire batch may not be. This should be especially true if those batches include migrations external packages.

**Comment by freost** [comment]
Yeah that makes sense. 

I guess the easiest way to check for support is to add a `supportsTransactional DDL()` method to the connection classes. And maybe have a `$useTransaction` (default true) property in the transaction classes so that it can be disabled as well.

**Comment by letr0n** [comment]
It would be nice to add support for multiple databases as well. We have a couple of apps that use more than a single database and it would be awesome to have all migrations in the same app.

```php reactor migrate.up```

```php reactor migrate.up --database=foobar```

**Comment by freost** [comment]
Yeah that would be another nice addition to the migration functionality. I'll be adding both features for the 5.6 release.

**Comment by freost** [comment]
Transaction support has been added in the master branch (currently only for Postgres). Support for multiple databases has also been added.
