### ISSUE TITLE
Atomic getOrElse is hangs fpm/apache with APCU

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#244]
###  Description
---
Due to [this issue](https://github.com/krakjoe/apcu/issues/246) in APCU, Apache and PHP-FPM will hang when using atomic getOrElse. This issue has been fixed upstream, but only in version 5.1.12 and up. The problem was introduced in APCU 5.1.8.

Unfortunately, Ubuntu 18.04 ships APCU 5.1.9, which means that quite a few users will be affected until someone back-ports this fix. So instead, I propose a workaround: an opt-out (or potentially opt-in) to atomic caching, by way of a config value in the cache definition.

If you'd like, I can produce a patch come Thursday. Let me know what you think.

###  Steps to reproduce
---

See linked issue. In framework terms, any page that will call `$cache->getOrElse()`.

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.2.7                    |
| Mako Version | 5.5.7                    |
| OS           | Ubuntu 18.04 |
| Database     | Irrelevant, but PostgreSQL 9.6  |

**Comment by freost** [comment]
Sounds good to me. I think an optional opt-out config option for the APCU store would be the best solution.
