### ISSUE TITLE
Cast result of arithmetic on columns to correct type in Query

### ISSUE THREAD

**Issue by mathysie** [mako-framework/framework#248]
###  Description
---

Methods like `Query::sum()` always return integers or floats. However, a string containing the integer is returned. Thus, boolean operators in the SQL-query fail to resolve to true, as an integer is compared against a string. This happens in SQLite 3.

###  Steps to reproduce
---

Create a SQLite-database with an integer column `foo` having value 1 and `bar` with value 2 in table 'foobar'. Then
```php
$query->table('foobar')->where('foo', '<', function($query) {$query->sum('bar')})->first();
```
returns `false`, where it needs to return the recently constructed row.

I can upload a pull request where `min`, `max`, `sum`, `avg`, `count` and `countDistinct` are cast correctly.

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.x.x                    |
| Mako Version | 5.x.x                    |
| OS           | -                        |
| Database     | SQLite 3                        |

**Comment by freost** [comment]
I don't think the query builder supports a closure as the third parameter. You would have to use `where` with a raw expression or `whereRaw`.

```$query->table('foobar')->whereRaw('foo', '<', 'SUM(bar)'})->first()```

**Comment by mathysie** [comment]
I think I gave the wrong example. This code is part of a query in our application:
```php
$query->where(
    new Raw('bedrag - korting'),
    '>',
    models\IncassoBatch::join(
        'machtigingen',
        'incasso_batches.incasso_id',
        '=',
        'machtigingen.incasso_id'
    )
    ->where('voldaan', '=', true)
    ->sum('drempel')
);
```
When using SQLite, the `sum` returns a string where `new Raw(...)` returns an integer in the compiled SQL. Casting `Query::sum` to integer lets both compile to integer in SQL.

**Comment by mathysie** [comment]
That sounds like a good idea. Thanks!
