### ISSUE TITLE
Can I access gatekeeper from any view? 

### ISSUE THREAD

**Issue by Herikle** [mako-framework/framework#250]
I know that it's not a forum here. But I need help and I can't find any solution on documentation. I can't check, for example, if a user is logged in a view?

```tpl.php
{% if(isLoggedIn()) %}
    <h1> I can't do that </h1>
{% endif %}
```
in laravel i have
```blade.php
@if (Auth::check())
    <h1> I can do that </h1>
@endif
```

**Comment by freost** [comment]
You have to assign the gatekeeper object to your views.

```php
// Assign it to the view you're rendering

$this->view->render('my-view', ['gatekeeper' => $this->gatekeeper]);

// Assign it globally to all views 
// (this can be done in a base controller or in the bootstrap file).

$this->view->assign('gatekeeper', $this->gatekeeper);
```

 You can also install the `helpers` [package](https://github.com/mako-framework/helpers) and access the gatekeeper instance like this:

```php
{% if(gatekeeper()-> isLoggedIn()) %}
    I'm logged in!
{% endif %}
```
