### ISSUE TITLE
Set exit status for "migrate.status" task

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#254]
###  Description
---

It would be very useful if the exit code of `migrate.status` would reflect the current migration status. This would make it easier for automated tools (such as deploy scripts) to check and warn when a migration needs to be run. The most "natural" way of doing this I think is to consider "no migrations" the normal state, and "outstanding migrations" the error state.

Code-wise, I think this would be a very simple addition since #200 has been implemented. It would technically break backwards compatibility but only really for code that assumes the exit code for `migrate.status` is always zero. Which I hope no-one does.

**Comment by freost** [comment]
It is generally considered bad practice to return non-zero exit codes for scripts that ran successfully. We should at least avoid using any of the reserved exit codes (http://www.tldp.org/LDP/abs/html/exitcodes.html)

**Comment by freost** [comment]
Looks like `git diff` has a `exit-code` option (I guess it gets added automatically when using `quiet`). Maybe that would be the best solution here as well?

` migrate.status --exit-code` would exit with `0` for no migrations and `1` if there are any. Without the option set it will continue to exit with `0` in both cases.

**Comment by bertptrs** [comment]
That would close out the automated usage case that I argued for, so I think that would be a nice solution.

**Comment by freost** [comment]
Implemented in 5.7.1 (b1e15f4a80f2db46f9908bc503efe85b87865e9c)
