### ISSUE TITLE
Defining routing doesn't work. He always shows the welcom page.

### ISSUE THREAD

**Issue by woisks** [mako-framework/framework#256]
mako 6.0
Defining routing doesn't work. He always shows the welcom page.
```
mako \ http \ exceptions \ NotFoundException (404)
GET:
```

**Comment by letr0n** [comment]
We have been using the 6.0 branch for months and have not encountered any issues. What web server are you using and which PHP version?

**Comment by freost** [comment]
Hi,

I'm unable to reproduce the issue. I need some more information regarding your routes and setup.

**Comment by woisk** [comment]
I used php7.3, development environment suite laragon 3, Ng, routing function doesn't work

**Comment by woisk** [comment]
What kind of environment do you use? I have been using laravel before, but some of them are too bulky and poor performance.

**Comment by freost** [comment]
Does it work with 5.7? There have been no changes to the routing between 5.7 and 6.0 and we have served millions of page views using 6.0 since the release a couple of weeks ago.

I have never heard of laragon but I'll have a look at it tomorrow.

**Comment by freost** [comment]
I installed laragon on a Windows 10 VM and set up a Mako test app and routing worked as expected.
