### ISSUE TITLE
Request::determinePath() only returns latest element in the path

### ISSUE THREAD

**Issue by alexiooo** [mako-framework/framework#259]
###  Description
---
Request::determinePath() Will only return the latest element of the request path (e.g. /login for /user/login). Causing routing to return 404 (as it tries to match /login).

The cause seems to be that 
`$basePath = pathinfo($server['SCRIPT_NAME'], PATHINFO_DIRNAME);`
contains everything except the latest element (e.g. /user for /user/login), which is later stripped.

...

###  Steps to reproduce
---
Try to access any route that is not directly under '/'.

...

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.2.18 (php-7.2-apache docker image)                    |
| Mako Version | 6.0.0                    |
| OS           | Linux (running dockerized containers) |
| Database     | -                        |

**Comment by freost** [comment]
I'm unable to reproduce this. Can you post the value of the `$_SERVER` super global?

**Comment by alexiooo** [comment]
PHP_SCRIPT contains '/user/login'
Others:
-- | --
HTTP_CONNECTION | "close"
CONTENT_LENGTH | "307"
HTTP_USER_AGENT | "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
HTTP_ACCEPT | "*/*"
HTTP_ACCEPT_LANGUAGE | "en-US,en;q=0.5"
HTTP_ACCEPT_ENCODING | "gzip, deflate"
HTTP_REFERER | "http://localhost/"
CONTENT_TYPE | "multipart/form-data; boundary=---------------------------139453559613765182981142697058"
HTTP_ORIGIN | "http://localhost"
HTTP_DNT | "1"
HTTP_COOKIE | "maze_session=b3e3daeef2250f5a2c8f3ddadb9671b70739b6f91288559c3668feb9019e84e5f04f10b18920c3dfc26a6919ae75696c2fb8a5d6b2b5e18201ee80a38370a340; felt_session=d3a63e4b4d3ba77601ac323ebf4c5a714a8ff01c677ca461889c84cbeec9fd5fac85d4d2640d1f1056e3182afaa5de701a33ebcf76e0edca9cde6d4782dd269f"
PATH | "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
SERVER_SIGNATURE | "<address>Apache/2.4.25 (Debian) Server at api Port 80</address>\n"
SERVER_SOFTWARE | "Apache/2.4.25 (Debian)"
SERVER_NAME | "api"
SERVER_ADDR | "172.18.0.3"
SERVER_PORT | "80"
REMOTE_ADDR | "172.18.0.6"
DOCUMENT_ROOT | "/var/www/html"
REQUEST_SCHEME | "http"
CONTEXT_PREFIX | ""
CONTEXT_DOCUMENT_ROOT | "/var/www/html"
SERVER_ADMIN | "webmaster@localhost"
SCRIPT_FILENAME | "/var/www/html/app/web.php"
REMOTE_PORT | "34738"
GATEWAY_INTERFACE | "CGI/1.1"
SERVER_PROTOCOL | "HTTP/1.0"
REQUEST_METHOD | "POST"
QUERY_STRING | ""
REQUEST_URI | "/user/login"
SCRIPT_NAME | "/user/login"
PHP_SELF | "/user/login"
REQUEST_TIME_FLOAT | 1558024342.663
REQUEST_TIME | 1558024342
argv | []
argc | 0

**Comment by freost** [comment]
There seems to be some issue with how the REQUEST_URI, SCRIPT_NAME, PHP_SELF values get populated. Whats the value of the `cgi.fix_pathinfo` setting in php.ini?

**Comment by alexiooo** [comment]
My bad, I've found the issue to be with using apache's Alias to redirect all requests to the index.php file. Using a nginx + pgp-fpm setup seems to have solved the issue.
