### ISSUE TITLE
Implement PSR-16 in the caching interface

### ISSUE THREAD

**Issue by bertptrs** [mako-framework/framework#262]
###  Description
---
Mako has its own Cache classes that provide general purpose caching. However, most PHP libraries are not dependent on Mako and thus will not support its caching interface directly.

It would be nice if the `mako\cache\StoreInterface` implementeded either [PSR-16 Simple Cache](https://github.com/php-fig/simple-cache) which is very similar in functionality or PSR-6 which is a whole different beast.

This way, we can more easily integrate existing libraries into Mako.

**Comment by freost** [comment]
The only issue I have with this is that CacheInterface returns `null` on cache misses while StoreInterface returns `false`

**Comment by bertptrs** [comment]
I think that in general `null` would be better to return in that case than `false` but that debate is hairy and I don't want to repeat the one that's happened with this standard.

In either case, I created [a package](https://github.com/bertptrs/mako-simple-cache) for now that does the wiring. If (a variation of) this could be included in a future Mako version that would be wonderful. Alternatively, the current `StoreInterface` could become an extension of the PSR-16 `CacheInterface`.

**Comment by freost** [comment]
Yeah I agree but changing it now would be a drastic bc break. I'll put it down as a change for Mako 7 (and I want to do the same for the database library since it also returns false if no record is returned).

I'll include something similar to your package in the 6.1 release.

**Comment by letr0n** [comment]
There were minor BC-breaks in the version 5 series of the framework. Is changing from `false` to `null` too big of a BC-break? I looked at our code and a guesstimate is that it would take about 30 minutes to an hour to update our codebase.

**Comment by freost** [comment]
I think it's best to wait until 7.0 as this change is more subtle than renaming a method. The plan is to bump the version when PHP 7.2 reaches EOL.

**Comment by freost** [comment]
This took a while but I have published a Simple Cache package https://github.com/mako-framework/simple-cache
