### ISSUE TITLE
Request::getIP does not work without `REMOTE_ADDR`

### ISSUE THREAD

**Issue by wgevaert** [mako-framework/framework#270]
###  Description
---
When doing our unit tests, we set up a localhost mako server. For some reason (I am not that familiar with all this) the `\mako\http\Request::$server->get('REMOTE_ADDR')` returns `null`. Currently, this breaks because then `null` is fed into `\mako\http\Request::isTrustedProxy`, triggering an error.
I guess the expected behaviour is that `Request::getIp()` returns `127.0.0.1` instead of throwing an error.
...

###  Steps to reproduce
---
- Set up a localhost
- Use `getIp` on a request from the localhost.
...

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.2.19                    |
| Mako Version | 6.3.0                    |
| OS           | Bionic Beaver                        |
| Database     | psql 10.10                        |

**Comment by freost** [comment]
Thanks 👍. It's fixed in 6.3.1.
