### ISSUE TITLE
Question: Pass parameter from Middleware to Controller

### ISSUE THREAD

**Issue by altsniffer** [mako-framework/framework#273]
Hi

I want to send parameter from Middleware back to Controller, in this example some user data.
Is this secure enough or is there another way of sending it to my Controller?

    // Middleware
    public function execute ( Request $request, Response $response, Closure $next ): Response {
	    // $userObject = getUserData() 
            $request->user = $userObject;
	    return $next( $request, $response );
    }

    // Controller
    $this->request->user

regards

**Comment by freost** [comment]
Hi,

You can what you have done or use the [`setAttribute` and `getAttribute`](https://api.makoframework.com/6.3.0/mako/http/Request.html#method_setAttribute) methods.

**Comment by altsniffer** [comment]
ok, it was that easy hehe thank you :)
