### ISSUE TITLE
Session persistence issue

### ISSUE THREAD

**Issue by netlinkingdev** [mako-framework/framework#277]
Hello
###  Description
---
I am having a problem I think regarding session persistence.
Using the `$this->session->put()` library doesn't seem to keep the element in session. And regarding `putFlash()` it doesn't save anything in flash session.
I use the sessions with the default configuration, file recording and not database.

The sessions are not persisted it would seem.
...
Thank you.

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.2.18                    |
| Mako Version | 6.3.11                    |
| OS           | -  Windows 10                    |
| Database     | -  MySQL                      |

**Comment by freost** [comment]
Hi,

I'm guessing that it doesn't work because `app/storage/sessions` is either missing or your app isn't permitted to write to the directory.

**Comment by netlinkingdev** [comment]
Hi,

I have the files that are written in the storage/sessions directory.
The permissions are well existing I don't understand.

**Comment by freost** [comment]
If the data is being written to disk but you're unable to retrieve it then it's probably a cookie issue.
