### ISSUE TITLE
Monolog 2

### ISSUE THREAD

**Issue by ossigeno** [mako-framework/framework#278]
###  Description
---
Is Monolog 2  support on the roadmap for Mako Framework? I am seeing a number of Monolog handlers that only work with Monolog 2
...

**Comment by freost** [comment]
Hi,

The next release (7.0) will use monolog 2. I hope to have it ready in a
couple of weeks.

man. 3. aug. 2020 kl. 13:40 skrev ossigeno <notifications@github.com>:

**Comment by freost** [comment]
Mako 7.0 with monolog 2 has been released.
