### ISSUE TITLE
Upgrading from Mako 6 to 7 OrderByRaw parameters changed

### ISSUE THREAD

**Issue by ossigeno** [mako-framework/framework#280]
Upgrading documentation doesn't mention that the Ouery class orderByRaw function requires new $parameters parameter

Mako 6
public function orderByRaw($raw, string $order = 'ASC')

Mako 7
public function orderByRaw($raw, array $parameters = [], string $order = 'ASC')

**Comment by freost** [comment]
Thanks. I have updated the docs.
