### ISSUE TITLE
server fails in complicated filepaths

### ISSUE THREAD

**Issue by wgevaert** [mako-framework/framework#281]
###  Description
---
When I run `php app/reactor server` in the directory `/home/me/my mako application/` it fails with the description `Directory /home/me/my does not exist.` which is mildly annoying. 

The problem is that in `src/mako/application/cli/commands/server/Server.php` the `__DIR__` is not escaped. I do not entirely know what kind of escaping should be used, as it is somewhat platform-specific. Replacing a lot of characters with the `\x..`-equivalents should work well, but I hope PHP has a builtin for this that I could not find.

Of course you have the same problem if you use other weird characters in filenames, such as newlines etc, but that is less common than spaces.
###  Steps to reproduce
---
Make a directory with a space in the name, put your mako application in one of its child dirs, then run the server.

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.4.3                    |
| Mako Version | 6.3.12                    |
| OS           | Linux (Focal)              |
| Database     | Postgres                        |

**Comment by wgevaert** [comment]
When I changed [this line](https://github.com/mako-framework/framework/blob/1ca121b6a5dd28192b0ecf4469fd5e18c581f062/src/mako/application/cli/commands/server/Server.php#L117) to 
`passthru(escapeshellarg(PHP_BINDIR . '/php') . " -S {$address}:{$availablePort} -t " . escapeshellarg($docroot) . ' ' . escapeshellarg(__DIR__ . "/router.php"));` it did work again.

**Comment by wgevaert** [comment]
I made a PR on the 6.3 branch. I think we can also apply it to master and 7.0, but I do not really understand how that would work so I hope someone can explain that.

**Comment by freost** [comment]
Fixed by #282
