### ISSUE TITLE
\database\midgard\relations\BelongsTo::getRelated seems to be broken.

### ISSUE THREAD

**Issue by wgevaert** [mako-framework/framework#285]
###  Description
---
On our branch to port to mako 7, I encountered weird behaviour of the BelongsTo relation.

We have an ORM 'Activiteit' and an ORM 'Inschrijving', and 'Inschrijving' has a belongsTo relation with activiteit.
When I tried to get the `activiteit` of a (non-persisted) `inschrijving`, I got some unrelated activity with id `1` instead of the related activity with id `3`.

This seems to be a severe bug. I have to investigate a bit further, but I already reported because of the severity.
...

###  Steps to reproduce
---
Make a database with a child-class and a parent-class, for example
```php
namespace app\models;

use mako\database\midgard\ORM;
use mako\database\midgard\traits\NullableTrait;
use mako\database\midgard\traits\OptimisticLockingTrait;

class MyChildClass extends ORM
{
    use NullableTrait;
    use OptimisticLockingTrait;

    public function parent()
    {
        return $this->belongsTo(MyParentClass::class);
    }
}
```
and 
```php
namespace app\models;

use mako\database\midgard\ORM;
use mako\database\midgard\traits\NullableTrait;
use mako\database\midgard\traits\OptimisticLockingTrait;

class MyParentClass extends ORM
{
    use NullableTrait;
    use OptimisticLockingTrait;

    public function childs()
    {
        return $this->hasMany(Child::class);
    }
}
```
And do something like this:
```php
namespace app\controllers;

use app\models\MyParentClass;
use app\models\MyChildClass;
use mako\http\routing\Controller;

class Index extends Controller
{
    public function welcome(): string
    {
        $parent = new MyParentClass;
        $parent->save();
        $parent->reload();

        $child = new MyChildClass;
        $child->my_parent_class_id = $parent->id;

        return $child->parent->id . " ==? " . $child->my_parent_class_id;
    }
}
```
In my experience, the returned numbers (with the `==?` in between) should always be equal. However, the left is always `1` and the right increments every time I call this controller method.

P.S. My (sqlite in this example) database looks a bit like this:
``` sql
CREATE TABLE my_parent_classes (
    id             INTEGER PRIMARY KEY,

    lock_version   INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE my_child_classes (
    id                  INTEGER PRIMARY KEY,
    my_parent_class_id  INTEGER NOT NULL REFERENCES parents (id),

    lock_version        INTEGER NOT NULL DEFAULT 0
);
```
...

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.4.3                    |
| Mako Version | 7.1.1                    |
| OS           | ubuntu (Focal)            |
| Database     | psql                        |

**Comment by wgevaert** [comment]
The bug does not exist in 6.3

**Comment by wgevaert** [comment]
The child being non-persisted seems to be very relevant. When doing a `save` before the `__get('parent')` everything works as expected.

**Comment by wgevaert** [comment]
The problem can be traced back to [this commit](https://github.com/mako-framework/framework/commit/42126ced9f45a4c9a9581ffcab4c53d78d376bee) where an additional `if ($parent->isPersisted()) {}` is added arount `$this->lazyCriterion()` in `mako\database\midgard\relations\Relation::__construct()`.

I am not confident enought to revert that change. Please have a look.

**Comment by wgevaert** [comment]
I guess it should be `$model->isPersisted` instead of `$parent->isPersisted` (or `origin->isPersisted` in mako 7 jargon). The lazy criterion uses `origin/parent -> getPrimaryKey` and `model->getForeignKey`.
It does make sense for a non-persisted model to have a foreign key set, but it does not make sense for a non-persisted model to have a primaryKey set.

**Comment by freost** [comment]
Hi,

I'll try to fix this as soon as possible but I have to make sure that it doesn't affect any of the other features. I hope that persisting the model before calling the relationships works a a temporary workaround 😅

**Comment by freost** [comment]
The "belongs to" relation is the only relation that worked without persisting the model so I'm leaning towards requiring models to be persisted before using relations. I will however make a change so it doesn't load a random record.

**Comment by wgevaert** [comment]
Yes I can then go fix my code. It seems no one else is having this issue for some reason :no_mouth: so that's okay.

**Comment by freost** [comment]
7.0.7 and 7.1.2 will now throw an  exception to prevent unexpected behavior.
