### ISSUE TITLE
Return type of File::read() incorrect

### ISSUE THREAD

**Issue by evroon** [mako-framework/framework#288]
###  Description
The [read](https://github.com/mako-framework/framework/blob/master/src/mako/session/stores/File.php#L90) function of File has a return type of `array`, but uses the [`unserialize`](https://www.php.net/manual/en/function.unserialize.php) function which can also return a boolean if the input is not unserializeable.  This will lead to the exception:

```
Return value of mako\session\stores\File::read() must be of the type array, boolean returned
```

###  Steps to reproduce
Try to read a sessionId that is in a file of which the contents can not be unserialized.

**Comment by freost** [comment]
Can't reproduce. An exception is thrown when `unserialize` fails:

```Uncaught ErrorException: unserialize(): Error at offset 21 of 126 bytes```
