### ISSUE TITLE
FileSystem copy method removed?

### ISSUE THREAD

**Issue by ossigeno** [mako-framework/framework#293]
###  Description
---
Documentation references Copy method which no longer exists on FileSystem
https://makoframework.com/docs/8.0/learn-more:file-system#file_system
...

###  Steps to reproduce
---

...

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 8.1.0                    |
| Mako Version | 8.0.2                   |
| OS           | MacOS                   |
| Database     | MariaDb                     |

**Comment by freost** [comment]
Hi,

The method should be available in 7.3+
https://github.com/mako-framework/framework/blob/master/src/mako/file/FileSystem.php#L150-L153
If you recently upgraded then you might have to reindex the project for your IDE to pick it up

**Comment by ossigeno** [comment]
Sorry. My mistake. I still have one project using Mako 6.
