### ISSUE TITLE
Monolog breaking change

### ISSUE THREAD

**Issue by ossigeno** [mako-framework/framework#299]
###  Description
---
Monolog addRecord method signature has changed
https://github.com/Seldaek/monolog/issues/1684#issue-1265966896

This is causing exception in Mako:
```
ErrorException: Compile Error (64)
Declaration of mako\logger\Logger::addRecord(int $level, string $message, array $context = []): bool 
must be compatible with 
Monolog\Logger::addRecord(int $level, string $message, array $context = [], ?Monolog\DateTimeImmutable $datetime = null): bool
```
...

###  Steps to reproduce
---
Update Mako project to 8.1
and run composer update
...

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 8.1.6                    |
| Mako Version | 8.1.0                    |
| OS           | macOS Monterey                        |
| Database     | MariaDb                       |

**Comment by freost** [comment]
A temporary solution is to lock the monolog version to `2.6.0` in your composer.json file. I'll make a permanent fix based on the outcome of the issue in the monolog repo.

**Comment by freost** [comment]
Fixed by changing the Mako logger to a LoggerInterface decorator instead of extending the Monolog Logger.
