### ISSUE TITLE
Can't rollback database migrations

### ISSUE THREAD

**Issue by lsfratel** [mako-framework/framework#309]
###  Description
---
Can't rollback database migration

###  Steps to reproduce
---

- Create a migration `php app/reactor migration:create`
- Edit the migration
- Run `php app/reactor migration:up`
- Rolls back the last batch of migrations  `php app/reactor migration:down`

### Links
---
**[Errors](https://pastebin.com/raw/rFLFXrD0)**
**[Migration](https://pastebin.com/raw/hRm8t9zA)**

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 8.1.x                    |
| Mako Version | 9.0.x                    |
| OS           | Linux Mint 21.1                       |
| Database     | 5.5.5-10.8.2-MariaDB-1:10.8.2+maria~focal                        |

**Comment by freost** [comment]
Fixed in 9.0.3
