### ISSUE TITLE
Feature Form Builder?

### ISSUE THREAD

**Issue by altsniffer** [mako-framework/framework#84]
How about a form builder in mako 4, with error handling and pre populate?
Most of the Frameworks have one, might be worth considering about an internal form builder?

<pre>

$form = new Form('action','method','class');
$form->addField('Text', 'firstname', ['class' => 'text-input']);
$form->addField();
$form->addField();
$form->addCustom();
$form->addHtml();

$user = User::get(1);
$form->populate($user->toArray());

or with Post

$form->populate($this->request->post());

$form->render(); 

</pre>

**Comment by letr0n** [comment]
I have started working on a form builder for fun. I'll release it as a stand-alone package if I'm happy with the result.

**Comment by mnishihan** [comment]
I don't think features like stand alone form builder should go into core of a framework, which in turn will make the core bloated with less frequently used stuffs. Also there exists, very good form builder package such as [Former](https://github.com/Anahkiasen/former), that can be integrated into any of the modern frameworks that uses composer for class/library loading.

**Comment by letr0n** [comment]
I agree. I planned to release it as a stand-alone package if I ever get around to finish it.
